name: Real Turbo
author: Hack at UCI
description: Better version of turbo-ignore from vercel/turborepo

inputs:
  task:
    description: The task to execute
    default: "build"
  workspace:
    required: true
    description: The workspace to filter on
outputs:
  status:
    description: "Status is 0 if changes can be ignored, 1 if changes should be deployed."
    value: ${{ steps.run_script.outputs.status}}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        # History must include parent commit for comparison
        # For pull requests, HEAD is a merge commit, so the parent is the base branch
        # For pushes, the parent commit must be the previous deployment,
        # so rebase merges must be disabled in the repository settings
        # This comparison also assumes the previous deployment succeeded
        fetch-depth: 2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Run script
      id: run_script
      env:
        # See Security hardening: Good practices for mitigating script injection attacks
        TASK: ${{ inputs.task }}
        WORKSPACE: ${{ inputs.workspace }}
      shell: bash
      run: |
        v=$(bun ${{ github.action_path }}/super-turbo-ignore.ts $TASK $WORKSPACE)
        echo "status=${v}" >> $GITHUB_OUTPUT
